# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinedtrip',
            name='trip_id',
        ),
        migrations.DeleteModel(
            name='JoinedTrip',
        ),
    ]
